version: '3.1'

services:
  db:
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    container_name: ${COMPOSE_PROJECT_NAME}_db
  web:
    build:
      context: ./
      args:
        "USER_ID": ${USER_ID}
        "GROUP_ID": ${GROUP_ID}
    command: bash -c "python manage.py migrate --noinput &&
                      python manage.py loaddata */fixtures/*.json &&
                      python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./web/web.env
    volumes:
      - ../../:/concert_tickets
    ports:
      - 8000:8000
    depends_on:
      - db
    container_name: ${COMPOSE_PROJECT_NAME}_backend

volumes:
  db_volume:
